### ISSUE TITLE
Create a read-inventory API which returns inventory info about a certain product

### ISSUE THREAD

**Issue by MingshiPeng** [NYUDevOpsInventory/inventory#10]
**As a** Inventory Manager,
**I need** to know the quantity of a certain product in the inventory.
**So that** I can keep track of product info in the inventory.

**Assumption:**
* The prod_id is given and valid when calling the API.

**Acceptance Criteria:**
```
Given a prod_id,
When the API is called,
Then the inventory information of the corresponding product will be returned.
```

**Comment by majia67** [comment]
@MingshiPeng Should we allow uses to read inventory info by "prod_name"? I think this API is intended for reading only one inventory at a time. I guess it is better to implement searching by "prod_name" as a query?

**Comment by majia67** [comment]
Looks like this API has already been implemented in a previous PR. Better close it?
