### ISSUE TITLE
Create a data model for Inventory entries.

### ISSUE THREAD

**Issue by MingshiPeng** [NYUDevOpsInventory/inventory#12]
A placeholder issue.

**Comment by jockyxu1122** [comment]
For minimal requirement, I think we just need `Product Category ID` (aka. `SKU` suggested by Professor), `New Products Quantity`, `Used Products Quantity`, `Open-boxed Products Quantity`, `Restock Level`, and `Restock Amount`.
Using MySQL, a single table is enough.

**Comment by MingshiPeng** [comment]
database model column names
* prod_id
* prod_name
* new_qty
* used_qty
* open_boxed_qty
* restock_level
* restock_amt
