### ISSUE TITLE
Setup database and create table(s).

### ISSUE THREAD

**Issue by jockyxu1122** [NYUDevOpsInventory/inventory#14]
**As an** Inventory team developer.
**I need** to setup data table(s).
**So that** product information can be stored.

**Assumption:**
* Data model is finalized, at least for minimal requirement.
* Vagrant environment is set up.

**Acceptance Criteria:**
```
Successfully install database service.
Data table(s) are established.
Given product information.
When CRUD operations are requested.
Then correct information from data table(s) is returned/modified.
```

**Comment by majia67** [comment]
We decided to use SQLAlchemy as our database management system.

**Comment by SaniyaLalani** [comment]
![img_3458](https://user-images.githubusercontent.com/24996322/36566494-a3b31546-17f1-11e8-87c4-ce9641aca5db.jpg)
