### ISSUE TITLE
Discuss API names and signatures

### ISSUE THREAD

**Issue by jockyxu1122** [NYUDevOpsInventory/inventory#16]
**As a** Inventory team developer.
**I need** API names and signatures finalized.
**So that** I can start implementing tests and features.

**Assumption:**
* Basic functionalities are discussed and finalized.

**Acceptance Criteria:**
```
Given API names and signatures.
When one of the APIs is called.
Then expected functionality is triggered.
```

**Comment by majia67** [comment]
root call: GET /
list-all: GET /inventory
read: GET /inventory/{prod_id}
create: POST /inventory
update: PUT /inventory/{prod_id}
delete: DELETE /inventory/{prod_id}
query: GET /inventory?{prod_name|quantity|condition=val}
category: GET
