### ISSUE TITLE
Creating two inventories with the same id could break sqlite

### ISSUE THREAD

**Issue by majia67** [NYUDevOpsInventory/inventory#23]
Here are the steps to reproduce the bug:
1. Launch the virtual machine and start the "server.py" file.
2. Call API "POST http://localhost:5000/inventory" with a JSON data. Make sure the "prod_id" and "prod_name" fields are given. A 201 response should be returned.
3. Call the same API again. A 500 response should be returned, indicating the failure of the database update.
4. Call the same API again, this time changing the "prod_id" to something else. Still a 500 response is returned. The expected response should be a 201.

Potential fix:
Do the "prod_id" uniqueness check when creating a new inventory record in the database.

**Comment by majia67** [comment]
After some initial investigation, I think it's better to finish basic API implementations first. Simply adding a "prod_id" lookup before calling "deserialize" could fix this bug.

**Comment by majia67** [comment]
@jockyxu1122 why this issue is dragged into "Review/QA" pipeline? Have you submitted a PR for fixing this bug?

**Comment by jockyxu1122** [comment]
@majia67 this issue is more like wrapped by #6 . Can't really separate these 2 issues apart with 2 PRs. I have included tests for this API. Current PR (connected to issue #6 ) would be enough to solve this issue.

**Comment by jockyxu1122** [comment]
@majia67 I don't think I have implemented test cases for adding duplicate entries in PR #24 . I'll create another PR for adding those tests.
