### ISSUE TITLE
Create a module for storing constants.

### ISSUE THREAD

**Issue by MingshiPeng** [NYUDevOpsInventory/inventory#27]
**As a** programmer,
**I need** to create a module for storing frequently used constants.
**So that** I don't have to create them over and over again.

**Assumption:**
* We need to reuse constants such as API urls & default property values.

**Acceptance Criteria:**
```
The module is created & all other modules can access the constants successfully.
```

**Comment by majia67** [comment]
we could put the constants in "models.py" and import the constants we need in other .py files.

**Comment by MingshiPeng** [comment]
The issue is trivial now as all constants are in their rightful place.
