### ISSUE TITLE
Create a new Space for Prod in the Cloud Foundary

### ISSUE THREAD

**Issue by jockyxu1122** [NYUDevOpsInventory/inventory#90]
**As a** team developer
**I need** a separate space for deployed production from development space.
**So that** our deployed app can run in an independent environment.

**Assumption:**
* Pipeline set up.

**Acceptance Criteria:**
```
Given our Inventory production
When changes happen in development space
Then the deployed production running in the separate environment is not affected.
```

**Comment by MingshiPeng** [comment]
New space named "Prod" created in Bluemix.
